export const OTP_PURPOSE_LABELS = {
  login: 'AUTH_LOGIN',
  register: 'AUTH_REGISTER',
  change_phone: 'AUTH_PHONE_CHANGE',
  delete_account: 'AUTH_DELETE_ACCOUNT',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_PHONE: 'PHONE_INVALID',
  UNSUPPORTED_COUNTRY: 'PHONE_UNSUPPORTED_COUNTRY',
  RATE_LIMITED: 'RATE_LIMITED',
  BLOCKED: 'BLOCKED',
  INVALID_CODE: 'INVALID_CODE',
  CODE_EXPIRED: 'CODE_EXPIRED',
  CODE_ALREADY_USED: 'CODE_ALREADY_USED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  UNDERAGE: 'UNDERAGE',
  RESEND_COOLDOWN: 'RESEND_COOLDOWN',
  MAX_RESENDS: 'MAX_RESENDS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SESSION_INVALID: 'SESSION_INVALID',
  OTP_DELIVERY_FAILED: 'OTP_DELIVERY_FAILED',
  WHATSAPP_NOT_AVAILABLE: 'WHATSAPP_NOT_AVAILABLE',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
